# Generated by Django 4.2.4 on 2023-08-30 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insert_coin_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesorios',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='otras_consolas',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='ps5',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='xbox_series_x',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
