# Generated by Django 4.2.4 on 2023-09-01 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insert_coin_app', '0002_accesorios_precio_alter_otras_consolas_precio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesorios',
            options={'verbose_name': 'Accesorios', 'verbose_name_plural': 'Accesorios'},
        ),
        migrations.AlterModelOptions(
            name='otras_consolas',
            options={'verbose_name': 'Otras Consolas', 'verbose_name_plural': 'Otras Consolas'},
        ),
        migrations.AlterModelOptions(
            name='ps5',
            options={'verbose_name': 'PS5', 'verbose_name_plural': 'PS5'},
        ),
        migrations.AlterModelOptions(
            name='socios',
            options={'verbose_name': 'Socios', 'verbose_name_plural': 'Socios'},
        ),
        migrations.AlterModelOptions(
            name='xbox_series_x',
            options={'verbose_name': 'XBOX', 'verbose_name_plural': 'XBOX'},
        ),
        migrations.AlterField(
            model_name='accesorios',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='otras_consolas',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='ps5',
            name='online',
            field=models.BooleanField(choices=[(True, 'Si'), (False, 'No')]),
        ),
        migrations.AlterField(
            model_name='ps5',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='xbox_series_x',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
