# Generated by Django 4.2.4 on 2023-09-02 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insert_coin_app', '0003_alter_accesorios_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Accesorios',
        ),
    ]
