# Generated by Django 4.2.4 on 2023-09-02 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insert_coin_app', '0004_delete_accesorios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otras_consolas',
            name='plataforma',
            field=models.CharField(choices=[('PS4', 'PS4'), ('XBOX ONE', 'XBOX ONE'), ('Nintendo Switch', 'Nintendo Switch'), ('PC', 'PC')], max_length=30),
        ),
    ]
